/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagos;


import co.edu.udec.poo.ComedorInfantil.Controladores.Pagos.ListarControladorPagos;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Pagos.ListarCasoDeUsoPagos;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Pagos.ListarPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Pagos.ListarRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.PagosCrud;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navid Lobato
 */
public class VentanaListarPagos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaListarPagadores
     */
    private ListarControladorPagos controlador;
    public VentanaListarPagos(ListarControladorPagos controlador) {
        this.controlador=controlador;
        initComponents();
        MostrarTodos();
    }
    
    
      public void MostrarTodos() {
        try {
            ListarRespuestaDto respuesta = controlador.ejecutarAccion();
            mostrarEnTabla(respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
    }

    public void mostrarEnTabla(ListarRespuestaDto respuesta) {
        DefaultTableModel tabla = new DefaultTableModel();
        
        //tabla.addColumn("Id");
        tabla.addColumn("Fecha");
        //tabla.addColumn("Costo Total");
        //tabla.addColumn("Costo FIjo");
        tabla.addColumn("Costo Comida");
        tabla.addColumn("Identificacion Nino");
        tabla.addColumn("Identificacion Pagador");
        
        for ( ListarPeticionDto p: respuesta.getPeticion()) {
            tabla.addRow(new Object[]{
                p.getFecha(), 
                p.getCostoComida(),
                p.getIdentificacion(), 
                p.getDniPagador()
                
            });
        }
        tablaPagos.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        PagosCrud pcrud = new PagosCrud(); 
        ListarCasoDeUsoPagos casoDeUso = new ListarCasoDeUsoPagos(pcrud);
        ListarControladorPagos controlador = new ListarControladorPagos(casoDeUso);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaListarPagos dialog = new VentanaListarPagos(controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPagos;
    // End of variables declaration//GEN-END:variables
}
