/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui.Comedor;

import co.edu.udec.poo.ComedorInfantil.Controladores.Comedor.ListarControladorComedor;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Comedor.ListarCasoDeUsoComedor;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Comedor.ListarPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Comedor.ListarRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.ComerCrud;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navid Lobato
 */
public class VentanaListarComedor extends javax.swing.JDialog {

    /**
     * Creates new form VentanaListarComedor
     */
    private ListarControladorComedor controlador;

    public VentanaListarComedor(ListarControladorComedor controlador) {
        this.controlador = controlador;
        initComponents();
        MostrarTodos();
    }

    public void MostrarTodos() {
        try {
            ListarRespuestaDto respuesta = controlador.ejecutarAccion();
            mostrarEnTabla(respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
    }

    public void mostrarEnTabla(ListarRespuestaDto respuesta) {
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Fecha");
        tabla.addColumn("IdentificaciónNino");
        tabla.addColumn("NumMenu");
        tabla.addColumn("Cantidad");

        for (ListarPeticionDto p : respuesta.getPeticion()) {
            tabla.addRow(new Object[]{
                p.getFecha(),
                p.getIdentificacionNino(),
                p.getNumeroMenu(),
                p.getCantComidas()

            });
        }
        tablaComedor.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaComedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaComedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListarComedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListarComedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListarComedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListarComedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
         ComerCrud cCrud = new ComerCrud(); 
        ListarCasoDeUsoComedor casoDeUso = new ListarCasoDeUsoComedor(cCrud);
        ListarControladorComedor controlador = new ListarControladorComedor(casoDeUso);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaListarComedor dialog = new VentanaListarComedor(controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaComedor;
    // End of variables declaration//GEN-END:variables
}
