/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui;

/**
 *
 * @author Navid Lobato
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuNinos = new javax.swing.JMenu();
        itemRegistrarNinos = new javax.swing.JMenuItem();
        itemEliminarNinos = new javax.swing.JMenuItem();
        itemEditarNinos = new javax.swing.JMenuItem();
        itemConsultarNinos = new javax.swing.JMenuItem();
        itemMostrarNinos = new javax.swing.JMenuItem();
        menuMenus = new javax.swing.JMenu();
        itemRegistrarMenus = new javax.swing.JMenuItem();
        itemAgregarMenus = new javax.swing.JMenuItem();
        itemAgregarPlatoMenus = new javax.swing.JMenuItem();
        itemMostrarMenus = new javax.swing.JMenuItem();
        menuPlatos = new javax.swing.JMenu();
        itemRegistrarPlatos = new javax.swing.JMenuItem();
        itemAgregarPlatos = new javax.swing.JMenuItem();
        itemAgregarIngredientePlatos = new javax.swing.JMenuItem();
        itemMostrarPlatos = new javax.swing.JMenuItem();
        menuPagadores = new javax.swing.JMenu();
        itemRegistrarPagadores = new javax.swing.JMenuItem();
        itemAsignarPagadores = new javax.swing.JMenuItem();
        itemCambiarnumCuentaPagadores = new javax.swing.JMenuItem();
        itemBuscarPagadores = new javax.swing.JMenuItem();
        itemMostrarPagadores = new javax.swing.JMenuItem();
        menuPagos = new javax.swing.JMenu();
        itemRegistrarPagos = new javax.swing.JMenuItem();
        itemGenerarPagos = new javax.swing.JMenuItem();
        itemMostrarPagos = new javax.swing.JMenuItem();
        menuBuscador = new javax.swing.JMenu();
        itemRegistrarBuscador = new javax.swing.JMenuItem();
        itemAsignarBuscador = new javax.swing.JMenuItem();
        itemMostrarBuscador = new javax.swing.JMenuItem();
        menuComedor = new javax.swing.JMenu();
        itemRegistrarComedor = new javax.swing.JMenuItem();
        itemMostrarComedor = new javax.swing.JMenuItem();
        itemContarComedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaPrincupal");

        menuNinos.setText("Niños");
        menuNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNinosActionPerformed(evt);
            }
        });

        itemRegistrarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarNinos.setText("Registrar...");
        itemRegistrarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemRegistrarNinos);

        itemEliminarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEliminarNinos.setText("Eliminar...");
        itemEliminarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemEliminarNinos);

        itemEditarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditarNinos.setText("Editar datos...");
        itemEditarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemEditarNinos);

        itemConsultarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemConsultarNinos.setText("Consultar bajas...");
        itemConsultarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemConsultarNinos);

        itemMostrarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarNinos.setText("Mostrar todos...");
        itemMostrarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemMostrarNinos);

        barraMenu.add(menuNinos);

        menuMenus.setText("Menus");
        menuMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarMenus.setText("Registrar ...");
        menuMenus.add(itemRegistrarMenus);

        itemAgregarMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarMenus.setText("Agregar...");
        itemAgregarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemAgregarMenus);

        itemAgregarPlatoMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarPlatoMenus.setText("Agregar plato...");
        itemAgregarPlatoMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPlatoMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemAgregarPlatoMenus);

        itemMostrarMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarMenus.setText("Mostrar menus...");
        itemMostrarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemMostrarMenus);

        barraMenu.add(menuMenus);

        menuPlatos.setText("Platos");
        menuPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPlatos.setText("Registrar ...");
        menuPlatos.add(itemRegistrarPlatos);

        itemAgregarPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarPlatos.setText("Agregar...");
        itemAgregarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemAgregarPlatos);

        itemAgregarIngredientePlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarIngredientePlatos.setText("Agregar ingrediente");
        itemAgregarIngredientePlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarIngredientePlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemAgregarIngredientePlatos);

        itemMostrarPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPlatos.setText("Mostrar platos...");
        itemMostrarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemMostrarPlatos);

        barraMenu.add(menuPlatos);

        menuPagadores.setText("Pagadores");
        menuPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPagadores.setText("Registrar ...");
        menuPagadores.add(itemRegistrarPagadores);

        itemAsignarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAsignarPagadores.setText("Asignar pagador...");
        itemAsignarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemAsignarPagadores);

        itemCambiarnumCuentaPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemCambiarnumCuentaPagadores.setText("Cambiar num cuenta...");
        itemCambiarnumCuentaPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambiarnumCuentaPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemCambiarnumCuentaPagadores);

        itemBuscarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarPagadores.setText("Buscar..");
        itemBuscarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemBuscarPagadores);

        itemMostrarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPagadores.setText("Mostrar todos ...");
        itemMostrarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemMostrarPagadores);

        barraMenu.add(menuPagadores);

        menuPagos.setText("Pagos");
        menuPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPagos.setText("Registrar ...");
        menuPagos.add(itemRegistrarPagos);

        itemGenerarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGenerarPagos.setText("Generar pago...");
        itemGenerarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenerarPagosActionPerformed(evt);
            }
        });
        menuPagos.add(itemGenerarPagos);

        itemMostrarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPagos.setText("Mostar todos...");
        itemMostrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPagosActionPerformed(evt);
            }
        });
        menuPagos.add(itemMostrarPagos);

        barraMenu.add(menuPagos);

        menuBuscador.setText("Buscador");
        menuBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarBuscador.setText("Registrar ...");
        menuBuscador.add(itemRegistrarBuscador);

        itemAsignarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAsignarBuscador.setText("Asignar buscador...");
        itemAsignarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarBuscadorActionPerformed(evt);
            }
        });
        menuBuscador.add(itemAsignarBuscador);

        itemMostrarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarBuscador.setText("Mostrar todos...");
        itemMostrarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarBuscadorActionPerformed(evt);
            }
        });
        menuBuscador.add(itemMostrarBuscador);

        barraMenu.add(menuBuscador);

        menuComedor.setText("Comedor");
        menuComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarComedor.setText("Registrar ...");
        menuComedor.add(itemRegistrarComedor);

        itemMostrarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarComedor.setText("Mostrar todos ....");
        itemMostrarComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarComedorActionPerformed(evt);
            }
        });
        menuComedor.add(itemMostrarComedor);

        itemContarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemContarComedor.setText("Contar comidas ...");
        itemContarComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContarComedorActionPerformed(evt);
            }
        });
        menuComedor.add(itemContarComedor);

        barraMenu.add(menuComedor);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEliminarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarNinosActionPerformed
        // TODO add your handling code here:
        
        VentanaEliminarNinos ventana= new VentanaEliminarNinos();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarNinosActionPerformed

    private void itemEditarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarNinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditarNinosActionPerformed

    private void itemConsultarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarNinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarNinosActionPerformed

    private void itemAgregarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarMenusActionPerformed

    private void itemAgregarPlatoMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPlatoMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarPlatoMenusActionPerformed

    private void itemMostrarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarMenusActionPerformed

    private void itemAgregarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarPlatosActionPerformed

    private void itemAgregarIngredientePlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarIngredientePlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarIngredientePlatosActionPerformed

    private void itemMostrarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarPlatosActionPerformed

    private void itemAsignarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarPagadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAsignarPagadoresActionPerformed

    private void itemCambiarnumCuentaPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambiarnumCuentaPagadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCambiarnumCuentaPagadoresActionPerformed

    private void itemBuscarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPagadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarPagadoresActionPerformed

    private void itemGenerarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenerarPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGenerarPagosActionPerformed

    private void itemMostrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarPagosActionPerformed

    private void itemAsignarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAsignarBuscadorActionPerformed

    private void itemMostrarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarBuscadorActionPerformed

    private void itemMostrarComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarComedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarComedorActionPerformed

    private void itemContarComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContarComedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemContarComedorActionPerformed

    private void itemMostrarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPagadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMostrarPagadoresActionPerformed

    private void itemRegistrarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarNinosActionPerformed
                    // TODO add your handling code here:
                    VentanaNinos ventana= new VentanaNinos();
                    ventana.setLocationRelativeTo(this);
                    ventana.setVisible(true);
                    
    }//GEN-LAST:event_itemRegistrarNinosActionPerformed

    private void itemMostrarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarNinosActionPerformed
        // TODO add your handling code here:
        VentanaMostrar ventana= new VentanaMostrar();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarNinosActionPerformed

    private void menuNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNinosActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_menuNinosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemAgregarIngredientePlatos;
    private javax.swing.JMenuItem itemAgregarMenus;
    private javax.swing.JMenuItem itemAgregarPlatoMenus;
    private javax.swing.JMenuItem itemAgregarPlatos;
    private javax.swing.JMenuItem itemAsignarBuscador;
    private javax.swing.JMenuItem itemAsignarPagadores;
    private javax.swing.JMenuItem itemBuscarPagadores;
    private javax.swing.JMenuItem itemCambiarnumCuentaPagadores;
    private javax.swing.JMenuItem itemConsultarNinos;
    private javax.swing.JMenuItem itemContarComedor;
    private javax.swing.JMenuItem itemEditarNinos;
    private javax.swing.JMenuItem itemEliminarNinos;
    private javax.swing.JMenuItem itemGenerarPagos;
    private javax.swing.JMenuItem itemMostrarBuscador;
    private javax.swing.JMenuItem itemMostrarComedor;
    private javax.swing.JMenuItem itemMostrarMenus;
    private javax.swing.JMenuItem itemMostrarNinos;
    private javax.swing.JMenuItem itemMostrarPagadores;
    private javax.swing.JMenuItem itemMostrarPagos;
    private javax.swing.JMenuItem itemMostrarPlatos;
    private javax.swing.JMenuItem itemRegistrarBuscador;
    private javax.swing.JMenuItem itemRegistrarComedor;
    private javax.swing.JMenuItem itemRegistrarMenus;
    private javax.swing.JMenuItem itemRegistrarNinos;
    private javax.swing.JMenuItem itemRegistrarPagadores;
    private javax.swing.JMenuItem itemRegistrarPagos;
    private javax.swing.JMenuItem itemRegistrarPlatos;
    private javax.swing.JMenu menuBuscador;
    private javax.swing.JMenu menuComedor;
    private javax.swing.JMenu menuMenus;
    private javax.swing.JMenu menuNinos;
    private javax.swing.JMenu menuPagadores;
    private javax.swing.JMenu menuPagos;
    private javax.swing.JMenu menuPlatos;
    // End of variables declaration//GEN-END:variables
}
