/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui;

import co.edu.udec.poo.ComedorInfantil.Controladores.BuscaNino.ListarControladorBuscadores;
import co.edu.udec.poo.ComedorInfantil.Controladores.Comedor.ListarControladorComedor;
import co.edu.udec.poo.ComedorInfantil.Controladores.Menus.ListarControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.ConsultarBajasControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.MostrarTodosControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Pagadores.ListarControladorPagadores;
import co.edu.udec.poo.ComedorInfantil.Controladores.Pagos.ListarControladorPagos;
import co.edu.udec.poo.ComedorInfantil.Controladores.Platos.ListarControladorPlatos;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.BuscaNino.ListarCasoDeUsoBuscadores;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Comedor.ListarCasoDeUsoComedor;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Menus.ListarCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.ConsultarBajasCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.MostrarTodosCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Pagadores.ListarCasoDeUsoPagadores;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Pagos.ListarCasoDeUsoPagos;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.MenuCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.NinosCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.PlatosCrud;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Menus.VentanaAggPlatoM;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Menus.VentanaMostrarTodosM;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Menus.VentanaRegistrarM;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos.VentanaBuscarAcciones;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos.VentanaConsultarBajas;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Platos.ListarCasoDeUsoPlatos;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.BuscaNinoCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.ComerCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.PagadorCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.PagosCrud;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.BuscaNino.VentanaAsignarBuscadores;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.BuscaNino.VentanaListarBuscadores;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.BuscaNino.VentanaRegistrarBuscadores;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Comedor.VentanaContarComedor;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Comedor.VentanaListarComedor;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Comedor.VentanaRegistrarComedor;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos.VentanaMostrarTodos;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos.VentanaRegistrar;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagadores.VentanaAsignarPagadore;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagadores.VentanaCambiarCuenta;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagadores.VentanaListarPagadores;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagadores.VentanaRegistrarPagadores;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagos.VentanaGenerarPago;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagos.VentanaListarPagos;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Pagos.VentanaRegistrarPagos;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Platos.VentanaAggIngreP;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Platos.VentanaListarP;
import co.edu.udec.poo.ComedorInfantil.vistas.gui.Platos.VentanaRegistrarP;

/**
 *
 * @author Navid Lobato
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuNinos = new javax.swing.JMenu();
        itemRegistrarNinos = new javax.swing.JMenuItem();
        itemBuscarAcciones = new javax.swing.JMenuItem();
        itemEditarNinos = new javax.swing.JMenuItem();
        itemConsultarNinos = new javax.swing.JMenuItem();
        itemMostrarNinos = new javax.swing.JMenuItem();
        menuMenus = new javax.swing.JMenu();
        itemRegistrarMenus = new javax.swing.JMenuItem();
        itemAgregarPlatoMenus = new javax.swing.JMenuItem();
        itemMostrarMenus = new javax.swing.JMenuItem();
        menuPlatos = new javax.swing.JMenu();
        itemRegistrarPlatos = new javax.swing.JMenuItem();
        itemAgregarIngredientePlatos = new javax.swing.JMenuItem();
        itemMostrarPlatos = new javax.swing.JMenuItem();
        menuPagadores = new javax.swing.JMenu();
        itemRegistrarPagadores = new javax.swing.JMenuItem();
        itemAsignarPagadores = new javax.swing.JMenuItem();
        itemCambiarnumCuentaPagadores = new javax.swing.JMenuItem();
        itemBuscarPagadores = new javax.swing.JMenuItem();
        itemMostrarPagadores = new javax.swing.JMenuItem();
        menuPagos = new javax.swing.JMenu();
        itemRegistrarPagos = new javax.swing.JMenuItem();
        itemGenerarPagos = new javax.swing.JMenuItem();
        itemMostrarPagos = new javax.swing.JMenuItem();
        menuBuscador = new javax.swing.JMenu();
        itemRegistrarBuscador = new javax.swing.JMenuItem();
        itemAsignarBuscador = new javax.swing.JMenuItem();
        itemMostrarBuscador = new javax.swing.JMenuItem();
        menuComedor = new javax.swing.JMenu();
        itemRegistrarComedor = new javax.swing.JMenuItem();
        itemMostrarComedor = new javax.swing.JMenuItem();
        itemContarComedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaPrincupal");

        menuNinos.setText("Niños");
        menuNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNinosActionPerformed(evt);
            }
        });

        itemRegistrarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarNinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Oxygen-Icons.org-Oxygen-Actions-list-add.24.png"))); // NOI18N
        itemRegistrarNinos.setText("Registrar...");
        itemRegistrarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemRegistrarNinos);

        itemBuscarAcciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarAcciones.setText("Buscar y realizar acciones");
        itemBuscarAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarAccionesActionPerformed(evt);
            }
        });
        menuNinos.add(itemBuscarAcciones);

        itemEditarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEditarNinos.setText("Editar datos...");
        itemEditarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemEditarNinos);

        itemConsultarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemConsultarNinos.setText("Consultar bajas...");
        itemConsultarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemConsultarNinos);

        itemMostrarNinos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarNinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarNinos.setText("Mostrar todos...");
        itemMostrarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarNinosActionPerformed(evt);
            }
        });
        menuNinos.add(itemMostrarNinos);

        barraMenu.add(menuNinos);

        menuMenus.setText("Menus");
        menuMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMenusActionPerformed(evt);
            }
        });

        itemRegistrarMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarMenus.setText("Registrar ...");
        itemRegistrarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemRegistrarMenus);

        itemAgregarPlatoMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarPlatoMenus.setText("Agregar plato...");
        itemAgregarPlatoMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPlatoMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemAgregarPlatoMenus);

        itemMostrarMenus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarMenus.setText("Mostrar menus...");
        itemMostrarMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarMenusActionPerformed(evt);
            }
        });
        menuMenus.add(itemMostrarMenus);

        barraMenu.add(menuMenus);

        menuPlatos.setText("Platos");
        menuPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarPlatos.setText("Registrar ...");
        itemRegistrarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarPlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemRegistrarPlatos);

        itemAgregarIngredientePlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAgregarIngredientePlatos.setText("Agregar ingrediente");
        itemAgregarIngredientePlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarIngredientePlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemAgregarIngredientePlatos);

        itemMostrarPlatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPlatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarPlatos.setText("Mostrar platos...");
        itemMostrarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPlatosActionPerformed(evt);
            }
        });
        menuPlatos.add(itemMostrarPlatos);

        barraMenu.add(menuPlatos);

        menuPagadores.setText("Pagadores");
        menuPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPagadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarPagadores.setText("Registrar ...");
        itemRegistrarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemRegistrarPagadores);

        itemAsignarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAsignarPagadores.setText("Asignar pagador...");
        itemAsignarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemAsignarPagadores);

        itemCambiarnumCuentaPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemCambiarnumCuentaPagadores.setText("Cambiar num cuenta...");
        itemCambiarnumCuentaPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambiarnumCuentaPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemCambiarnumCuentaPagadores);

        itemBuscarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarPagadores.setText("Buscar..");
        itemBuscarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemBuscarPagadores);

        itemMostrarPagadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPagadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarPagadores.setText("Mostrar todos ...");
        itemMostrarPagadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPagadoresActionPerformed(evt);
            }
        });
        menuPagadores.add(itemMostrarPagadores);

        barraMenu.add(menuPagadores);

        menuPagos.setText("Pagos");
        menuPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarPagos.setText("Registrar ...");
        itemRegistrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarPagosActionPerformed(evt);
            }
        });
        menuPagos.add(itemRegistrarPagos);

        itemGenerarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemGenerarPagos.setText("Generar pago...");
        itemGenerarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenerarPagosActionPerformed(evt);
            }
        });
        menuPagos.add(itemGenerarPagos);

        itemMostrarPagos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarPagos.setText("Mostar todos...");
        itemMostrarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPagosActionPerformed(evt);
            }
        });
        menuPagos.add(itemMostrarPagos);

        barraMenu.add(menuPagos);

        menuBuscador.setText("Buscador");
        menuBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarBuscador.setText("Registrar ...");
        itemRegistrarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarBuscadorActionPerformed(evt);
            }
        });
        menuBuscador.add(itemRegistrarBuscador);

        itemAsignarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemAsignarBuscador.setText("Asignar buscador...");
        itemAsignarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarBuscadorActionPerformed(evt);
            }
        });
        menuBuscador.add(itemAsignarBuscador);

        itemMostrarBuscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarBuscador.setText("Mostrar todos...");
        itemMostrarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarBuscadorActionPerformed(evt);
            }
        });
        menuBuscador.add(itemMostrarBuscador);

        barraMenu.add(menuBuscador);

        menuComedor.setText("Comedor");
        menuComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemRegistrarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemRegistrarComedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Registrar24PX.png"))); // NOI18N
        itemRegistrarComedor.setText("Registrar ...");
        itemRegistrarComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarComedorActionPerformed(evt);
            }
        });
        menuComedor.add(itemRegistrarComedor);

        itemMostrarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemMostrarComedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Mostrar24px.png"))); // NOI18N
        itemMostrarComedor.setText("Mostrar todos ....");
        itemMostrarComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarComedorActionPerformed(evt);
            }
        });
        menuComedor.add(itemMostrarComedor);

        itemContarComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemContarComedor.setText("Contar comidas ...");
        itemContarComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContarComedorActionPerformed(evt);
            }
        });
        menuComedor.add(itemContarComedor);

        barraMenu.add(menuComedor);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBuscarAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarAccionesActionPerformed
        // TODO add your handling code here:
        VentanaBuscarAcciones ventana = new VentanaBuscarAcciones();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);


    }//GEN-LAST:event_itemBuscarAccionesActionPerformed

    private void itemEditarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarNinosActionPerformed
        // TODO add your handling code here:
        VentanaBuscarAcciones ventana = new VentanaBuscarAcciones();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarNinosActionPerformed

    private void itemConsultarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarNinosActionPerformed
        // TODO add your handling code here:
        NinosCrud ninocrud = new NinosCrud(); 
        ConsultarBajasCasoDeUso casoDeUso = new ConsultarBajasCasoDeUso(ninocrud);
        ConsultarBajasControlador controlador = new ConsultarBajasControlador(casoDeUso);
        
        VentanaConsultarBajas ventana = new VentanaConsultarBajas(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);


    }//GEN-LAST:event_itemConsultarNinosActionPerformed

    private void itemAgregarPlatoMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPlatoMenusActionPerformed
        // TODO add your handling code here:
        VentanaAggPlatoM ventana = new VentanaAggPlatoM();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarPlatoMenusActionPerformed

    private void itemMostrarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarMenusActionPerformed
        // TODO add your handling code here:
         MenuCrud mcrud = new MenuCrud(); 
        ListarCasoDeUso casoDeUso = new ListarCasoDeUso(mcrud);
        ListarControlador controlador = new ListarControlador(casoDeUso);
        VentanaMostrarTodosM ventana = new VentanaMostrarTodosM(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarMenusActionPerformed

    private void itemAgregarIngredientePlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarIngredientePlatosActionPerformed
        // TODO add your handling code here:
        
        VentanaAggIngreP v = new VentanaAggIngreP ();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemAgregarIngredientePlatosActionPerformed

    private void itemMostrarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPlatosActionPerformed
        // TODO add your handling code here:
        PlatosCrud pcrud = new PlatosCrud(); 
        ListarCasoDeUsoPlatos casoDeUso = new ListarCasoDeUsoPlatos(pcrud);
        ListarControladorPlatos controlador = new ListarControladorPlatos(casoDeUso);
        
        VentanaListarP ventana= new VentanaListarP(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarPlatosActionPerformed

    private void itemAsignarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarPagadoresActionPerformed
        // TODO add your handling code here:
        VentanaAsignarPagadore ventana = new VentanaAsignarPagadore();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAsignarPagadoresActionPerformed

    private void itemCambiarnumCuentaPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambiarnumCuentaPagadoresActionPerformed
        // TODO add your handling code here:
        VentanaCambiarCuenta v = new VentanaCambiarCuenta();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemCambiarnumCuentaPagadoresActionPerformed

    private void itemBuscarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPagadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarPagadoresActionPerformed

    private void itemGenerarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenerarPagosActionPerformed
        // TODO add your handling code here:
        VentanaGenerarPago v = new VentanaGenerarPago();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemGenerarPagosActionPerformed

    private void itemMostrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPagosActionPerformed
        // TODO add your handling code here:
         PagosCrud pcrud = new PagosCrud(); 
        ListarCasoDeUsoPagos casoDeUso = new ListarCasoDeUsoPagos(pcrud);
        ListarControladorPagos controlador = new ListarControladorPagos(casoDeUso);
        VentanaListarPagos v = new VentanaListarPagos(controlador);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemMostrarPagosActionPerformed

    private void itemAsignarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarBuscadorActionPerformed
        // TODO add your handling code here:
        VentanaAsignarBuscadores v = new VentanaAsignarBuscadores();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemAsignarBuscadorActionPerformed

    private void itemMostrarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarBuscadorActionPerformed
        // TODO add your handling code here:
        BuscaNinoCrud bncrud = new BuscaNinoCrud(); 
        ListarCasoDeUsoBuscadores casoDeUso = new ListarCasoDeUsoBuscadores(bncrud);
        ListarControladorBuscadores controlador = new ListarControladorBuscadores(casoDeUso);
        VentanaListarBuscadores v= new VentanaListarBuscadores(controlador);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemMostrarBuscadorActionPerformed

    private void itemMostrarComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarComedorActionPerformed
        // TODO add your handling code here:
         ComerCrud cCrud = new ComerCrud(); 
        ListarCasoDeUsoComedor casoDeUso = new ListarCasoDeUsoComedor(cCrud);
        ListarControladorComedor controlador = new ListarControladorComedor(casoDeUso);
        VentanaListarComedor ventana = new VentanaListarComedor(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarComedorActionPerformed

    private void itemContarComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContarComedorActionPerformed
        // TODO add your handling code here:
         VentanaContarComedor v = new VentanaContarComedor();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        
    }//GEN-LAST:event_itemContarComedorActionPerformed

    private void itemMostrarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPagadoresActionPerformed
        // TODO add your handling code here:
        PagadorCrud mcrud = new PagadorCrud(); 
        ListarCasoDeUsoPagadores casoDeUso = new ListarCasoDeUsoPagadores(mcrud);
        ListarControladorPagadores controlador = new ListarControladorPagadores(casoDeUso);
        VentanaListarPagadores ventana = new VentanaListarPagadores(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarPagadoresActionPerformed

    private void itemRegistrarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarNinosActionPerformed
        // TODO add your handling code here:
        VentanaRegistrar ventana = new VentanaRegistrar();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);

    }//GEN-LAST:event_itemRegistrarNinosActionPerformed

    private void itemMostrarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarNinosActionPerformed
        // TODO add your handling code here:

        NinosCrud ninocrud = new NinosCrud(); 
        MostrarTodosCasoDeUso casoDeUso = new MostrarTodosCasoDeUso(ninocrud);
        MostrarTodosControlador controlador = new MostrarTodosControlador(casoDeUso);
        VentanaMostrarTodos ventana = new VentanaMostrarTodos(controlador);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemMostrarNinosActionPerformed

    private void menuNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNinosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_menuNinosActionPerformed

    private void menuMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMenusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuMenusActionPerformed

    private void itemRegistrarMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarMenusActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarM ventana = new VentanaRegistrarM();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistrarMenusActionPerformed

    private void itemRegistrarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarPlatosActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarP ventana = new VentanaRegistrarP();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistrarPlatosActionPerformed

    private void itemRegistrarPagadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarPagadoresActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarPagadores ventana = new VentanaRegistrarPagadores();
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemRegistrarPagadoresActionPerformed

    private void itemRegistrarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarPagosActionPerformed
        // TODO add your handling code here:
         VentanaRegistrarPagos v = new VentanaRegistrarPagos();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemRegistrarPagosActionPerformed

    private void itemRegistrarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarBuscadorActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarBuscadores v = new VentanaRegistrarBuscadores();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemRegistrarBuscadorActionPerformed

    private void itemRegistrarComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarComedorActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarComedor v = new VentanaRegistrarComedor();
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        
    }//GEN-LAST:event_itemRegistrarComedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemAgregarIngredientePlatos;
    private javax.swing.JMenuItem itemAgregarPlatoMenus;
    private javax.swing.JMenuItem itemAsignarBuscador;
    private javax.swing.JMenuItem itemAsignarPagadores;
    private javax.swing.JMenuItem itemBuscarAcciones;
    private javax.swing.JMenuItem itemBuscarPagadores;
    private javax.swing.JMenuItem itemCambiarnumCuentaPagadores;
    private javax.swing.JMenuItem itemConsultarNinos;
    private javax.swing.JMenuItem itemContarComedor;
    private javax.swing.JMenuItem itemEditarNinos;
    private javax.swing.JMenuItem itemGenerarPagos;
    private javax.swing.JMenuItem itemMostrarBuscador;
    private javax.swing.JMenuItem itemMostrarComedor;
    private javax.swing.JMenuItem itemMostrarMenus;
    private javax.swing.JMenuItem itemMostrarNinos;
    private javax.swing.JMenuItem itemMostrarPagadores;
    private javax.swing.JMenuItem itemMostrarPagos;
    private javax.swing.JMenuItem itemMostrarPlatos;
    private javax.swing.JMenuItem itemRegistrarBuscador;
    private javax.swing.JMenuItem itemRegistrarComedor;
    private javax.swing.JMenuItem itemRegistrarMenus;
    private javax.swing.JMenuItem itemRegistrarNinos;
    private javax.swing.JMenuItem itemRegistrarPagadores;
    private javax.swing.JMenuItem itemRegistrarPagos;
    private javax.swing.JMenuItem itemRegistrarPlatos;
    private javax.swing.JMenu menuBuscador;
    private javax.swing.JMenu menuComedor;
    private javax.swing.JMenu menuMenus;
    private javax.swing.JMenu menuNinos;
    private javax.swing.JMenu menuPagadores;
    private javax.swing.JMenu menuPagos;
    private javax.swing.JMenu menuPlatos;
    // End of variables declaration//GEN-END:variables
}
