package co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos;

import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.BuscarControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.EliminarControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.RegistrarseControlador;
import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.RetirarControlador;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.BuscarCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.EliminarCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.RegistrarseCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.RetirarCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.BuscarPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.BuscarRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.EliminarPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.EliminarRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.RegistrarsePeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.RetirarPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.NinosCrud;
import co.edu.udec.poo.ComedorInfantil.modelo.entidades.Ninos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;

/**
 *
 * @author Navid Lobato
 */
public class VentanaBuscarAcciones extends JDialog {

    /**
     * Creates new form VentanaBuscarParaEditar
     */
    public VentanaBuscarAcciones() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonIrVentanaEditarNinos = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonRetirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoBuscador = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonIrVentanaEditarNinos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonIrVentanaEditarNinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Editar24px.png"))); // NOI18N
        buttonIrVentanaEditarNinos.setText("EDITAR");
        buttonIrVentanaEditarNinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIrVentanaEditarNinosActionPerformed(evt);
            }
        });

        buttonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Eliminar24px.png"))); // NOI18N
        buttonEliminar.setText("ELIMINAR");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonRetirar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Retirar24Px.png"))); // NOI18N
        buttonRetirar.setText("RETIRAR");
        buttonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetirarActionPerformed(evt);
            }
        });

        tablaMostrar.setBackground(new java.awt.Color(153, 153, 153));
        tablaMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificaicon", "Matricula", "Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(tablaMostrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonIrVentanaEditarNinos)
                        .addGap(165, 165, 165)
                        .addComponent(buttonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRetirar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIrVentanaEditarNinos)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonRetirar))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR NINO A RELIZAR ACCION POR IDENTIFICACION:");

        buttonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/ComedorInfantil/vistas/iconos/Buscar24Px.png"))); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(campoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(buttonBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIrVentanaEditarNinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIrVentanaEditarNinosActionPerformed
        // TODO add your handling code here:
        String identificacion= campoBuscador.getText();
        VentanaEditar ventana;
        ventana = new VentanaEditar(identificacion);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buttonIrVentanaEditarNinosActionPerformed

    
    private void mostrarEnTabla(BuscarRespuestaDto respuesta) {
    DefaultTableModel tabla = new DefaultTableModel();
    tabla.addColumn("Nombre");
    tabla.addColumn("Identificación");
    tabla.addColumn("Nacimiento");
    tabla.addColumn("Matrícula");

    tabla.addRow(new Object[]{
        respuesta.getNombre(),
        respuesta.getIdentificacion(),
        respuesta.getNacimiento(),
        respuesta.getNumMatricula()
    });

    tablaMostrar.setModel(tabla);
}

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
        String identificacion =campoBuscador.getText();
        try {
            BuscarPeticionDto peticion = new BuscarPeticionDto(identificacion);
            NinosCrud ninosCrud = new NinosCrud();
            BuscarCasoDeUso casoDeUso = new BuscarCasoDeUso(ninosCrud);
            BuscarControlador controlador = new BuscarControlador(casoDeUso);
            BuscarRespuestaDto respuesta =controlador.ejecutarAccion(peticion);
            this.mostrarEnTabla(respuesta);
        } catch (Exception ex) {
            String msj = ex.getMessage();
            JOptionPane.showMessageDialog(this, msj, "Error al Buscar Niño", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
        String identificacion = campoBuscador.getText();
        try {
            EliminarPeticionDto peticion = new EliminarPeticionDto(identificacion);
            NinosCrud ninoscrud= new NinosCrud();
            EliminarCasoDeUso casoDeUso = new EliminarCasoDeUso(ninoscrud);
            EliminarControlador controlador = new EliminarControlador(casoDeUso); 
            controlador.ejecutarAccion(peticion);
            String msj ="Nino Eliminado con exito!";
            JOptionPane.showConfirmDialog(this, msj);
            
        } catch (Exception e) {
            String msj = e.getMessage();
            JOptionPane.showMessageDialog(this, msj, "Error al Eliminar Nino", JOptionPane.ERROR_MESSAGE);
        } finally {
            this.dispose();
        }
        
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetirarActionPerformed
        // TODO add your handling code here:
        
        String identificacion = campoBuscador.getText();
        try {
            RetirarPeticionDto peticion = new RetirarPeticionDto(identificacion);
            NinosCrud ninocrud= new NinosCrud();
            RetirarCasoDeUso casoDeUso = new RetirarCasoDeUso(ninocrud);
            RetirarControlador controlador = new RetirarControlador(casoDeUso);
            controlador.ejecutarAccion(peticion);
            String msj ="Nino Retirado con exito!";
            JOptionPane.showConfirmDialog(this, msj);
            
        } catch (Exception e) {
            String msj = e.getMessage();
            JOptionPane.showMessageDialog(this, msj, "Error al Retirar Niño", JOptionPane.ERROR_MESSAGE);
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_buttonRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaBuscarAcciones dialog = new VentanaBuscarAcciones();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonIrVentanaEditarNinos;
    private javax.swing.JButton buttonRetirar;
    private javax.swing.JTextField campoBuscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMostrar;
    // End of variables declaration//GEN-END:variables
}
