/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos;

import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.MostrarTodosControlador;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.MostrarTodosCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.BuscarRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.MostrarTodosPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.MostrarTodosRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.NinosCrud;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navid Lobato
 */
public class VentanaMostrarTodos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaMostrarTodos
     */
    private MostrarTodosControlador controlador;
    
    public VentanaMostrarTodos(MostrarTodosControlador controlador) {
        this.controlador=controlador;
        initComponents();
        MostrarTodos();
    }
      public void MostrarTodos() {
        try {
            MostrarTodosRespuestaDto respuesta = controlador.ejecutarAccion();
            mostrarEnTabla(respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
    }

    public void mostrarEnTabla(MostrarTodosRespuestaDto respuesta) {
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Nombre");
        tabla.addColumn("Identificación");
        tabla.addColumn("Estado");
        tabla.addColumn("Matricula");
        tabla.addColumn("FechaIngreso");
        tabla.addColumn("FechaBaja");
        tabla.addColumn("Nacimiento");
        for ( MostrarTodosPeticionDto peticion: respuesta.getPeticion()) {
            tabla.addRow(new Object[]{
                peticion.getNombre(),
                peticion.getIdentificacion(),
                peticion.getEstado(),
                peticion.getMatricula(),
                peticion.getFechaIngreso(),
                peticion.getFechaBaja(),
                peticion.getNacimiento()
            });
        }
        tablaMostrarTodos.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarTodos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaMostrarTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMostrarTodos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMostrarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMostrarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMostrarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMostrarTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
         NinosCrud ninocrud = new NinosCrud(); 
        MostrarTodosCasoDeUso casoDeUso = new MostrarTodosCasoDeUso(ninocrud);
        MostrarTodosControlador controlador = new MostrarTodosControlador(casoDeUso);
        VentanaMostrarTodos ventana = new VentanaMostrarTodos(controlador);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMostrarTodos dialog = new VentanaMostrarTodos(controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMostrarTodos;
    // End of variables declaration//GEN-END:variables
}
