/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.ComedorInfantil.vistas.gui.Ninos;

import co.edu.udec.poo.ComedorInfantil.Controladores.Ninos.ConsultarBajasControlador;
import co.edu.udec.poo.ComedorInfantil.modelo.CasosDeUso.Ninos.ConsultarBajasCasoDeUso;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.ConsultarBajasPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.ConsultarBajasRespuestaDto;
import co.edu.udec.poo.ComedorInfantil.modelo.Dto.Ninos.MostrarTodosPeticionDto;
import co.edu.udec.poo.ComedorInfantil.modelo.crud.NinosCrud;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navid Lobato
 */
public class VentanaConsultarBajas extends javax.swing.JDialog {

    /**
     * Creates new form VentanaConsultarBajas
     */
    private ConsultarBajasControlador controlador;
    public VentanaConsultarBajas(ConsultarBajasControlador controlador) {
        this.controlador = controlador;
        initComponents();
        mostrarTablaBajas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBajas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        tablaBajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Identificacion", "Estado", "Matricula", "Fecha Ingreso", "Fecha Baja", "Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(tablaBajas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ninos en de bajas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void mostrarTablaBajas(){
        try {
            ConsultarBajasRespuestaDto respuesta = controlador.ejecutarAccion();
            mostrarEnTabla(respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
        
    }
    
    public void mostrarEnTabla(ConsultarBajasRespuestaDto respuesta){
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Nombre");
        tabla.addColumn("Identificación");
        tabla.addColumn("Estado");
        tabla.addColumn("Matricula");
        tabla.addColumn("FechaIngreso");
        tabla.addColumn("FechaBaja");
        tabla.addColumn("Nacimiento");
        for ( ConsultarBajasPeticionDto peticion: respuesta.getPeticion()) {
            tabla.addRow(new Object[]{
                peticion.getNombre(),
                peticion.getIdentificacion(),
                peticion.getEstado(),
                peticion.getMatricula(),
                peticion.getFechaIngreso(),
                peticion.getFechaBajas(),
                peticion.getNacimiento()
            });
        }
        tablaBajas.setModel(tabla);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultarBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
         NinosCrud ninocrud = new NinosCrud(); 
        ConsultarBajasCasoDeUso casoDeUso = new ConsultarBajasCasoDeUso(ninocrud);
        ConsultarBajasControlador controlador = new ConsultarBajasControlador(casoDeUso);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaConsultarBajas dialog = new VentanaConsultarBajas(controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBajas;
    // End of variables declaration//GEN-END:variables
}
